.\" (C) Copyright 2023 Eugene E. Sorochinskiy <manager@darkguard.net>,
.\"
.TH KGLIFE 1 "October 03 2023" "Kglife project" "Game Of Life"
.SH NAME
kglife \- Game Of Life
.SH SYNOPSIS
.B kglife
.RI [ options ]
.SH DESCRIPTION
.B kglife
Another Game Of Life realization
.PP
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-H, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
