.\" (C) Copyright 2023 Eugene E. Sorochinskiy <manager@darkguard.net>,
.\"
.TH KGLIFE 1 "October 03 2023" "Проект Kglife" "Игра Жизнь"
.SH НАЗВАНИЕ
kglife \- Еще одна игра Жизнь
.SH СИНТАКСИС
.B kglife
.RI [ параметры ]
.SH ОПИСАНИЕ
.B kglife
Ещё одна реализация игры "Жизнь"
.PP
.SH ПАРАМЕТРЫ
Программа соблюдает обычный для GNU команд синтаксис, включая параметры с двумя дефисами (`-').
Краткий список параметров предоставлен ниже.
.TP
.B \-h, \-H, \-\-help
Показать список параметров.
.TP
.B \-v, \-\-version
Показать текущую версию программмы.
