.\" (C) Copyright 2023 Eugene E. Sorochinskiy <manager@darkguard.net>,
.\"
.TH KGLIFE 1 "October 03 2023" "Project Kglife" "Lebenspiel"
.SH NAME
kglife \- Die andere Lebenspielrealisation
.SH ÜBERSICHT
.B kglife
.RI [ Argumente ]
.SH BESCHREIBUNG
.B kglife
Jezt die andere Lebenspiel
.PP
.SH ARGUMENTE
Dieses Programm folgt der üblichen GNU-Befehlszeilensyntax mit langen
Argumenten, die mit zwei Bindestrichen (`-') anfangen.
Eine Argumentenzusammenfassung finden Sie unten.
.TP
.B \-h, \-H, \-\-help
Argumentenzusammenfassung einzeigen
.TP
.B \-v, \-\-version
App Version einzeigen
